name: seungjoon_utils
description: "내가 사용할 플러터 유틸리티 패키지"
version: 1.0.0
homepage: https://github.com/seungjoonH/seungjoon_utils

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: